### ISSUE TITLE
Nice code saya ini. Jangan Change Author lah Brody

### ISSUE THREAD

**Issue by MyFreds** [WavyCraftNetwork/Wind-Charge-PMMP-#1]

**Comment by WavyCraftNetwork** [comment]
Haha indeed cool code but I modified it so technically it's mine as well. Secondly I don't release plugins that aren't mine like this one while I did change the author and stuff I only did it so it fits with the WavyCraft branding and also I keep only legendary authors for respect. I admire your work but I'm not giving you credit. Farewell

**Comment by MyFreds** [comment]
> Haha indeed cool code but I modified it so technically it's mine as well. Secondly I don't release plugins that aren't mine like this one while I did change the author and stuff I only did it so it fits with the WavyCraft branding and also I keep only legendary authors for respect. I admire your work but I'm not giving you credit. Farewell

Okay, now I don't mind
